INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES ('register', 'register.last_name', 'Nom', NULL, '/creer-compte/etape/1', 24);
INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES ('register', 'register.postal_code', 'Code Postal', NULL, '/creer-compte/etape/1', 32);
INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES ('register', 'register.error_phone', 'Numéro téléphone/Mobile invalide, veuillez vérifier le préfixe s\'il vous plaît', NULL, '/creer-compte/etape/1', 46);
INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES ('register', 'register.invalid_phone', 'Numéro téléphone/Mobile invalide', NULL, '/creer-compte/etape/1', 26);
INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES ('registerfb', 'registerfb.bonjour', 'Bonjour', NULL, '/facebook-inscription/etape2', 0);


INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES
('annonce', 'required', 'Ce champ est obligatoire', 'This field is required', '/publiez-annonce-error', 60),
('annonce', 'email', 'Entrez une adresse email valide', 'Enter a valid mail address', '/publiez-annonce-error', 61),
('annonce', 'number', 'Entrez un nombre valide', 'Enter a valid number', '/publiez-annonce-error', 62),
('annonce', 'phone_error', 'Téléphone/Numero du mobile invalide', 'Invalid Phone/Mobile number', '/publiez-annonce-error', 63),
('annonce', 'description_error', 'Ce champ doit avoir au plus 2200 caractères.', 'This field must have a maximum of 2200 characters.', '/publiez-annonce-error', 64),
('annonce', 'number_only', 'S\'il vous plait entrez uniquement des nombres', 'Please enter numbers Only', '/publiez-annonce-error', 65),
('annonce', 'email_pris', 'Cet email est déjà pris', 'This email is already taken', '/publiez-annonce-error', 66),
('annonce', 'required_date_visit', 'La date de visite est obligatoire', 'The date of visit is mandatory', '/publiez-annonce-error', 67),
('annonce', 'format_date', 'Le format de la date n\'est pas correcte', 'The date format is not correct', '/publiez-annonce-error', 68),
('annonce', 'end_date_start_error', 'L\'heure de fin doit être une heure postérieure à l\'heure de début', 'The end time must be one hour later than the start time', '/publiez-annonce-error', 69),
('annonce', 'note_least', 'Ce champ doit avoir au moins 10 caractères', 'The end time must be one hour later than the start time', '/publiez-annonce-error', 70),
('erreur', 'email_invalid', 'Email invalide!', 'Email invalide!', '/erreur', 71),
('erreur', 'no_ad_found', 'Désolé! aucune annonce trouvé', 'Sorry! no ad found', '/erreur', 72),
('erreur', 'message_archived', 'Message archivé avec succès', 'Message archived successfully', '/erreur', 73),
('erreur', 'something_wrong', 'Désolé! On a rencontré un problème', 'Sorry! We encountered a problem', '/erreur', 74),
('erreur', 'message_deleted', 'Message supprimé avec succès', 'Message deleted successfully', '/erreur', 75),
('erreur', 'message_deleted', 'Message supprimé avec succès', 'Message deleted successfully', '/erreur', 76),
('erreur', 'no_blog_found', 'Désolé! Aucun blog trouvé', 'Sorry! No blog found', '/erreur', 77),
('erreur', 'deactivated_ad', 'Succès! Votre annonce :title a été désactivée', 'Success! Your ad: title has been deactivated', '/erreur', 78),
('erreur', 'actived_ad', 'Succès! Votre annonce :title a été activée', 'Success! Your ad: title has been activated', '/erreur', 79),
('erreur', 'ad_deleted', 'Succès! Votre annonce :title a été supprimée', 'Success! Your ad: title has been deleted', '/erreur', 80),
('erreur', 'ad_already_boosted', 'Désolé, cette annonce a été déjà boosté', 'Sorry, this ad has already been boosted', '/erreur', 81),
('erreur', 'max_allowed_file_size', 'Désolé! la taille maximum du fichier autorisé est : :size', 'Sorry! the maximum file size allowed is:: size', '/erreur', 82),
('erreur', 'ad_success_editing', 'Succès! Votre annonce a été modifiée et attend l\'approbation de l\'administrateur', 'Success! Your ad has been edited and is awaiting administrator approval', '/erreur', 83),
('erreur', 'ad_success_posted', 'Succès! Votre annonce a été postée et attend l\'approbation de l\'administrateur', 'Success! Your ad has been posted and is awaiting administrator approval', '/erreur', 84),
('erreur', 'loged_out_inactivity', 'Désolé! Vous avez été déconnécté à cause de votre longue inactivité! Veuillez réessayer', 'Sorry! You have been disconnected because of your long inactivity! Try Again', '/erreur', 85),
('erreur', 'session_not_valid', 'Désolé, votre session n\'est pas valide', 'Sorry, your session is not valid', '/erreur', 86),
('erreur', 'session_expired', 'Désolé, votre session a expiré! Veuillez réessayer', 'Sorry, your session has expired! Try Again', '/erreur', 87),
('erreur', 'request_canceled', 'Requête annulé avec succès', 'Request successfully canceled', '/erreur', 88),
('erreur', 'request_cant_canceled', 'Désolé! impossible d\'annuler. requête déjà accepté', 'Sorry! cannot cancel. request already accepted', '/erreur', 89),
('erreur', 'already_subscribed', 'Déjà abonné', 'Already subscribed', '/erreur', 90),
('erreur', 'subscribed_succesfully', 'Vous vous ête abonnés avec succès.', 'You have successfully subscribed.', '/erreur', 91),
('erreur', 'success_boost', '\":title\" Annonce boostée avec succès', '\": title\" Ad boosted successfully', '/erreur', 92),
('erreur', 'payment_success', 'Paiement avec succès', 'Successful payment', '/erreur', 93),
('erreur', 'profile_update_success', 'Votre profil a été modifié avec succès.', 'Your profile has been successfully modified.', '/erreur', 94),
('erreur', 'error_occured', 'On a rencontré des erreurs. Veuillez réessayer', 'We encountered some errors. Try Again', '/erreur', 95),
('erreur', 'email_verified', 'Email vérifié avec succès, Connectez-vous pour continuer.', 'Email verified successfully, Login to continue.', '/erreur', 96),
('erreur', 'email_verified_only', 'Email vérifié avec succès', 'Email verified successfully', '/erreur', 97),
('erreur', 'wrong_cred', 'Mauvaise identification, Veuillez réessayer', 'Wrong identification, please try again', '/erreur', 98),
('erreur', 'not_able_to_save', 'On n\'a pas pu enregistrer les informations , Veuillez réessayer.', 'Could not save information, please try again.', '/erreur', 99),
('erreur', 'reset_pass_check_mail', 'Un email a été envoyé sur votre boite pour réinitialiser votre mot de passe. Veuillez vérifier votre boite email', 'An email has been sent to your inbox to reset your password. Please check your email box', '/erreur', 100),
('erreur', 'account_not_verified', 'Votre compte n\'est pas encore vérifié, Cliquer sur le lien de vérification dans l\'email de vérification', 'Your account is not yet verified, Click on the verification link in the verification email', '/erreur', 101),
('erreur', 'account_not_active', 'Votre compte n\'est pas active. Essayer de contacter l\'administrateur du site!', 'Your account is not active. Try to contact the site administrator!', '/erreur', 102),
('erreur', 'success_reset_password', 'Votre mot de passe a été réinitialisé, Veuillez vous connecter.', 'Your password has been reset, please login.', '/erreur', 103),
('erreur', 'token_not_valid', 'Token non valide', 'Invalid token', '/erreur', 104),
('erreur', 'token_not_present', 'Token n\'est pas présente dans la requête', 'Token is not present in the request', '/erreur', 105),
('erreur', 'token_not_found', 'Token de réinitialisation de mot de passe non trouvé', 'Password reset token not found', '/erreur', 106),
('erreur', 'data_saved', 'Données sauvegardées avec succès', 'Data saved successfully', '/erreur', 107),
('erreur', 'connexion_required', 'Veuillez vous connecter ou créer votre compte s\'il vous plait', 'Please login or create your account', '/erreur', 108),
('erreur', 'you_are_robot', 'Vous n\'êtes pas un humain', 'You are not a human', '/erreur', 109),
('erreur', 'code_invalide', 'Ce code est invalide ou expirée', 'This code is invalid or expired', '/erreur', 110),
('erreur', 'code_valide', 'votre code promo est validé, vous bénificierez de toutes les fonctionnalités du site jusqu\'au :date', 'your promo code is validated, you will benefit from all the functionalities of the site until: date', '/erreur', 111),
('erreur', 'code_valide_promotion', 'votre code promo est validé, vous benificierez d\'une réduction de :number%', 'your promo code is validated, you will benefit from a reduction of: number%', '/erreur', 112),
('erreur', 'code_already_used', 'Vous utilisez déjà ce code', 'You are already using this code', '/erreur', 113),
('erreur', 'give_motivation', 'Vous devez donner une motivation.', 'You have to give motivation.', '/erreur', 114),
('erreur', 'must_auth', 'Vous devez vous authentifier', 'You must authenticate', '/erreur', 115),
('erreur', 'select_document_file', 'Vous devez sélectionner un fichier pour ce document', 'You must select a file for this document', '/erreur', 116),
('erreur', 'rectify_message', 'Il y a des erreurs lors du traitement du formulaire. Merci de les rectifier.', 'There are errors while processing the form. Please correct them.', '/erreur', 117),
('erreur', 'ad_desactive', 'Cette annonce a été désactivé', 'This ad has been disabled', '/erreur', 118),
('erreur', 'desactive_ad_fb', 'Si vous êtes propriétaire de l\'annonce, inscrivez-vous pour l\'activer, si vous n\'êtes pas propriétaire vous pouvez trouvez des annonces <a class=\'link-recherche-fb\' href=\'/colocation/ile-de-france/paris\'>en cliquant ici</a>', 'If you own the ad, subscribe to activate it, if you are not the owner you can find ads <a class = \'link-recherche-fb\' href = \'/ colocation / ile-de- france / paris\'> by clicking here </a>', '/erreur', 119),
('erreur', 'error_contact', 'Il est interdit de fournir des contacts dans les coordonnées', 'It is forbidden to provide contacts in contact details', '/erreur', 120),
('erreur', 'error_contact_ad', 'Il est interdit de mentionner vos coordonnées dans le titre et la description de l\'annonce, souhaitez-vous quand même continuer?', 'It is forbidden to mention your contact details in the title and description of the ad, do you still want to continue?', '/erreur', 121),
('erreur', 'email_verif_envoye', 'Un email de vérification vous a été envoyé, Cliquer sur le lien de vérification dans l\'email pour vérifier votre compte', 'A verification email has been sent to you, Click on the verification link in the email to verify your account', '/erreur', 122),
('erreur', 'none_facebook_account', 'Votre compte n\'est pas encore associé à un compte \" . config(\'app.name\', \"bailti\") . \". Veuillez vous inscrire avec ce compte <a class=\'link-surligne\' href=\'/creer-compte/etape/1\'>en cliquant ici</a>', 'Your account is not yet associated with a \". Config (\'app.name\',\" bailti \").\" Account. Please register with this account <a class=\'link-surligne\' href=\'/creer-compte/etape/1\'> by clicking here </a>', '/erreur', 123),
('erreur', 'email_facebook_required', 'Votre compte facebook doit être liée à une adresse email pour être utiliser sur \" . config(\'app.name\', \"bailti\")', 'Your facebook account must be linked to an email address to be used on \". Config (\'app.name\',\" bailti \")', '/erreur', 124),
('erreur', 'email_parainage_user', 'L\'email que vous avez saisi existe déjà dans la base de données', 'The email you entered already exists in the database', '/erreur', 125),
('erreur', 'email_parainage_bad_format', 'Adresse email invalide', 'Invalid email address', '/erreur', 126),
('erreur', 'duplicate_ad', 'Annonce dupliqué avec succès', 'Ad duplicated successfully', '/erreur', 127),
('erreur', 'email_confirmation', 'Un email a été envoyé sur votre adresse email. Veuillez valider votre adresse email en cliquant sur le lien que nous avons envoyés.', 'An email has been sent to your email address. Please validate your email address by clicking on the link we sent.', '/erreur', 128);