INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES
('login', 'login.registration_successful', 'Félicitation Inscription réussie. Vérifiez votre compte en cliquant sur le lien envoyé sur votre adresse email', 'Congratulation Successful registration. Verify your account by clicking on the link sent to your email address', '/connexion', 129),
('login', 'login.resend_mail', 'Cliquer ici pour renvoyer l\'email de verification', 'Click here to resend the verification email', '/connexion', 130),
('login', 'login.verif_mail_sent', 'Un email de vérification a été envoyé à :mail', 'A verification email has been sent to: mail', '/connexion', 131),
('login', 'login.registered_with', 'Bienvenu sur', 'Welcome to', '/connexion', 132),
('login', 'login.error_phone', 'Numéro téléphone/Mobile invalide, veuillez vérifier le préfixe s\'il vous plaît', 'Invalid phone / mobile number, please check the prefix please', '/connexion', 133),
('login', 'login.enter_phone', 'Entrer un numéro de téléphone/Mobile valide', 'Enter a valid phone / mobile number', '/connexion', 134),
('login', 'login.invalid_phone', 'Numéro téléphone/Mobile invalide', 'Invalid phone / mobile number', '/connexion', 135),
('email', 'hi', 'Bonjour', 'Hello', '/email', 136),
('email', 'title_registration', 'Nouvelle inscription d\'un utilisateur', 'New user registration', '/email', 137),
('email', 'thanks', 'Merci', 'Thank you', '/email', 138),
('email', 'perso_data_text', 'Veuillez retrouvez ci-joint votre données personnels', 'Please find attached your personal data', '/email', 139),
('email', 'code_groupe_message', 'Voici le code qui vous permettra de rejoindre le groupe : ', 'Here is the code that will allow you to join the group:', '/email', 140),
('email', 'activated_ad_message', 'Votre annonce \":title\" a été approuvé par l\'administrateur du site', 'Your ad \": title\" has been approved by the site administrator', '/email', 141),
('email', 'deactivated_ad_message', 'Votre annonce \":title\" a été désapprouvé par l\'administrateur du site', 'Your ad \": title\" has been deprecated by the site administrator', '/email', 142),
('email', 'welcome_create_annonce', 'On est heureux de vous rececvoir sur bailti, Créez votre annonce sur bailti maintenant', 'We are happy to receive you on bailti, Create your ad on bailti now', '/email', 143),
('email', 'complete_ad_text', 'Merci d\'avoir posté votre annonce sur bailti. Compléter votre annonce pour améliorer sa visibilité', 'Thank you for posting your ad on bailti. Complete your ad to improve its visibility', '/email', 144),
('email', 'newsletter_message', 'Merci d\'être inscrit sur notre newsletter.', 'Thank you for posting your ad on baa Thank you for subscribing to our newsletter.ilti. Complete your ad to improve its visibility', '/email', 145),
('email', 'message_acceuil', 'Merci pour votre inscription sur bailti.', 'Thank you for registering on bailti.', '/email', 146),
('email', 'thank_subscribing', 'Merci de vous être abonné à notre service', 'Thank you for subscribing to our service', '/email', 147),
('email', 'account_created', 'Félicitation et bienvenu votre compte a été crée .Il vous reste qu\'une dernière étape.', 'Congratulations and welcome, your account has been created. You just have one last step.', '/email', 148),
('email', 'reset_message', 'Votre demande de réinitialisation de mot de passe a bien été reçu. Cliquez sur le lien ci-dessous pour réinitialiser votre mot de passe.', 'Your request to reset your password has been received. Click on the link below to reset your password.', '/email', 149),
('email', 'cependant_click', 'Afin de valider votre adresse mail et que vos annonces soient visibles cliquez sur le lien ci-dessous :', 'In order to validate your email address and that your ads are visible click on the link below:', '/email', 150),
('email', 'faire_appel', 'Si vous voulez faire appel répondez sur ce mail en indiquant votre point de vu.', 'If you want to appeal, answer this email stating your point of view.', '/email', 151);