INSERT INTO `page_text` (`page`, `index`, `text_fr`, `text_en`, `url`, `ordre`) VALUES
('email', 'post_your_ad', 'Publier votre annonce maintenant sur bailti', 'Publish your ad now on bailti', '/email', 152),
('email', 'post_your_ad_link', 'Publier votre annonce', 'Publish your ad', '/email', 153),
('email', 'improve_ad', 'Améliorer votre annonce', 'Improve your ad', '/email', 154),
('email', 'mail_error_subject', 'Un érreur sur bailti', 'An error on bailti', '/email', 155),
('email', 'error_message', 'Vérfier s\'il vous plait, il y a un erreur sur notre site.', 'Please check, there is an error on our site.', '/email', 156),
('email', 'complete_profil_text', 'Votre profil est completé à :percent%, Complétez votre profil afin de multiplier les chances d\'être contacté .', 'Your profile is completed at :percent%, Complete your profile to increase the chances of being contacted.', '/email', 157),
('email', 'verify_account', 'Valider votre compte', 'Validate your account', '/email', 158),
('email', 'bien_a_vous', 'Bien à vous', 'Yours truly', '/email', 159),
('email', 'flash_message', 'Votre annonce a du succès. :first_name viens de vous envoyer un TocToc pour vous indiquer son intérêt.', 'Your ad is successful. : first_name just sent you a TocToc to indicate its interest.', '/email', 160),
('email', 'voir_profil', 'cliquant ici', 'click here', '/email', 161),
('email', 'voir_profil_message', 'Vous pouvez voir son profil en', 'You can see his profile in', '/email', 162),
('email', 'subs_detail', 'Vos détails d\'abonnement sont', 'Your subscription details are', '/email', 163),
('email', 'dear', 'Cher', 'Dear', '/email', 164),
('email', 'plan_amount', 'Montant du plan', 'Plan amount', '/email', 165),
('email', 'start_valid', 'votre abonnement est valide du', 'your subscription is valid from', '/email', 166),
('email', 'amount_paid', 'Montant payé', 'Payroll amount', '/email', 167),
('email', 'payment_detail', 'Détail du paiement', 'Payment details', '/email', 168),
('email', 'payment_success', 'Paiement avec succès', 'Successful payment', '/email', 169),
('email', 'complete_profile', 'Compléter profil', 'Complete profile', '/email', 170),
('email', 'visit_message', 'Votre annonce ', 'Your ad', '/email', 171),
('email', 'visit_message2', 'a reçu une demande de visite de la part de :first_name.', 'received a visit request from :first_name.', '/email', 172),
('email', 'visit_object', 'Demande de visite', 'Visit request', '/email', 173),
('email', 'consult_visit', 'Vous pouvez voir la liste de vos demandes de visite en', 'You can see the list of your visit requests in', '/email', 174),
('email', 'text_message_administrateur', 'Vous avez reçu un message de la part de l\'administrateur du site à propos de votre annonce intitulée \":title\"', 'You have received a message from the site administrator about your ad titled \" :title\"', '/email', 175),
('email', 'voir_ads_toctoc', 'Pour voir son annonce de recherche et signifier aussi votre intérêt, cliquez sur ce lien : ', 'To see his search ad and also indicate your interest, click on this link:', '/email', 176),
('email', 'annonce_search', 'Voir l\'annonce', 'See the announcement', '/email', 177),
('email', 'voir_ad_toctoc', 'Vous pouvez consulter son annonce en', 'You can view his ad in', '/email', 178),
('email', 'user_registration', 'Inscription d\'un utilisateur', 'User registration', '/email', 179),
('email', 'ad_creation', 'Création d\'une nouvelle annonce', 'Creation of a new ad', '/email', 180),
('email', 'new_application', 'a envoyé une candidature pour ', 'sent an application for', '/email', 181),
('email', 'view_application', 'Voir Canditdatures', 'See candidatures', '/email', 182),
('email', 'view_message', 'Voir message', 'View message', '/email', 183),
('email', 'send_message', 'a envoyé un message pour vous', 'sent a message for you', '/email', 184),
('email', 'new_message_subject', 'Nouveau message', 'New message', '/email', 185),
('email', 'new_application_subject', 'Nouvelle candidature', 'New application', '/email', 186),
('email', 'perso_data_subject', 'Données Personnels', 'Personal data', '/email', 187),
('email', 'code_groupe', 'Code d\'accès au groupe', 'Group access code', '/email', 188),
('email', 'ad_activation', 'Annonce approuvée', 'Ad approved', '/email', 189),
('email', 'ad_desactivation', 'Annonce désapprouvée', 'Announcement disapproved', '/email', 190),
('email', 'view_ad', 'Voir annonce', 'See ad', '/email', 191),
('email', 'create_annonce', 'Créez une annonce', 'Create an ad', '/email', 192),
('email', 'complete_ad', 'Compléter votre annonce', 'Complete your ad', '/email', 193);
