
INSERT INTO `page_text` ( `page`, `index`, `text_fr`, `text_en`, `url`, `ordre`, `text_fr_proposition`, `text_en_proposition`, `valide`, `commentaire`, `id_traducteur`) VALUES
('Mail_ad_expired', 'first_message_expired', 'Comme votre annonce a été publée il y a plus d\'un mois déjà,\r\nnous aurions besoin de savoir si elle est toujours\r\nd\'actualité. Afin d\'éviter aux visiteurs de perdre leur temps\r\net de vous déranger pour rien si cela n\'est pas le cas, votre\r\nannonce sera désactiver dans 7 jours à compter\r\nde la réception de ce message.', 'As your ad was published more than a month ago,\r\nwe would need to know if she is still\r\ntopical. To prevent visitors from wasting their time\r\nand to bother you for nothing if this is not the case, your\r\nannouncement will be deactivated in 7 days from\r\nupon receipt of this message.', '/delay-annonces-list-expired', 1, 'Comme votre annonce a été publée il y a plus d\'un mois déjà,\r\nnous aurions besoin de savoir si elle est toujours\r\nd\'actualité. Afin d\'éviter aux visiteurs de perdre leur temps\r\net de vous déranger pour rien si cela n\'est pas le cas, votre\r\nannonce sera désactiver dans 7 jours à compter\r\nde la réception de ce message.', 'As your ad was published more than a month ago,\r\nwe would need to know if she is still\r\ntopical. To prevent visitors from wasting their time\r\nand to bother you for nothing if this is not the case, your\r\nannouncement will be deactivated in 7 days from\r\nupon receipt of this message.', 1, NULL, NULL),
('Mail_ad_expired', 'second_message_expired', 'Si vous etes toujours en recherche, vous pouvez prolonger\r\nsa publication en cliquant sue le lien ci-desous:', 'If you are still looking, you can extend\r\nits publication by clicking on the link below:', '/delay-annonces-list-expired', 1, 'Si vous etes toujours en recherche, vous pouvez prolonger\r\nsa publication en cliquant sue le lien ci-desous:', 'If you are still looking, you can extend\r\nits publication by clicking on the link below:', 1, NULL, NULL),
('Mail_ad_expired', 'third_message_expired', 'Si vous avez déjà trouvé la perle rare ou n\'êtes plus\r\nen recherche, vous pouvez dès maintenant désactiver\r\nou supprimer votre annonce:', 'If you have already found the gem or are no longer\r\nin search, you can now deactivate\r\nor delete your ad:', '/delay-annonces-list-expired', 1, 'Si vous avez déjà trouvé la perle rare ou n\'êtes plus\r\nen recherche, vous pouvez dès maintenant désactiver\r\nou supprimer votre annonce:', 'If you have already found the gem or are no longer\r\nin search, you can now deactivate\r\nor delete your ad:', 1, NULL, NULL),
('Mail_ad_expired', 'message_connecter', 'Me connecter à mon compte', 'Login to my account', '/delay-annonces-list-expired', 1, 'Me connecter à mon compte', 'Login to my account', 1, NULL, NULL),
('Mail_ad_expired', 'message_reactiver', 'Réactiver mon annonce pour un mois supplémentaire', 'Reactivate my ad for an additional month', '/delay-annonces-list-expired', 1, 'Réactiver mon annonce pour un mois supplémentaire', 'Reactivate my ad for an additional month', 1, NULL, NULL),
('Mail_ad_desactive', 'first_message_desactive', 'Votre annonce a été publiée il y a plus d\'un mois déjà, et vous  n\'avez\r\ncliqué sur aucun des liens de réacivation envoyés par e-mail ces derniers jours.\r\n<b>Nous venons donc de la désactiver</b>, et elle ne sera dorénavant plus visible\r\npour les personnes en recherche.', 'Your ad was published more than a month ago, and you have\r\nclicked on none of the reactivation links emailed in recent days.\r\n<b> We have just deactivated it </b>, and it will no longer be visible\r\nfor people in research.', '/delay-annonces-list-desactive', 1, 'Votre annonce a été publiée il y a plus d\'un mois déjà, et vous  n\'avez\r\ncliqué sur aucun des liens de réacivation envoyés par e-mail ces derniers jours.\r\n<b>Nous venons donc de la désactiver</b>, et elle ne sera dorénavant plus visible\r\npour les personnes en recherche.', 'Your ad was published more than a month ago, and you have\r\nclicked on none of the reactivation links emailed in recent days.\r\n<b> We have just deactivated it </b>, and it will no longer be visible\r\nfor people in research.', 1, NULL, NULL),
('Mail_ad_desactive', 'second_message_desactive', 'Elle restera néanmoins présente dans votre compte, et vous pourrez à tout moment la\r\nréactiver, ou au contraire la supprimer définitivement, en vous y connectant :', 'It will nevertheless remain present in your account, and you can at any time\r\nreactivate, or on the contrary delete it permanently, by connecting to it:', '/delay-annonces-list-desactive', 1, 'Elle restera néanmoins présente dans votre compte, et vous pourrez à tout moment la\r\nréactiver, ou au contraire la supprimer définitivement, en vous y connectant :', 'It will nevertheless remain present in your account, and you can at any time\r\nreactivate, or on the contrary delete it permanently, by connecting to it:', 1, NULL, NULL),
('Mail_ad_desactive', 'politesse_message_desactive', 'Nous espérons sincèrement que le site vous aura été utile, à bientot!', 'We sincerely hope that the site will have been useful to you, see you soon!', '/delay-annonces-list-desactive', 1, 'Nous espérons sincèrement que le site vous aura été utile, à bientot!', 'We sincerely hope that the site will have been useful to you, see you soon!', 1, NULL, NULL),
('Reactivation_annoce_page', 'reactivation_annonce', 'Reactivation d\'annonce', 'Ad reactivation', '/reactiver-annonce/{id}.{email}', 1, 'Reactivation d\'annonce', 'Ad reactivation', 1, NULL, NULL),
('Reactivation_annoce_page', 'titre_annonce', 'Titre annonce', 'Ad Title', '/reactiver-annonce/{id}.{email}', 1, 'Titre annonce', 'Ad Title', 1, NULL, NULL),
('Reactivation_annoce_page', 'dernier_mise', 'Derniere mise à jour', 'Last update', '/reactiver-annonce/{id}.{email}', 1, 'Derniere mise à jour', 'Last update', 1, NULL, NULL),
('Reactivation_annoce_page', 'text_btn_reactivation', 'Reactiver l\'annonce', 'Reactivate the ad', '/reactiver-annonce/{id}.{email}', 1, 'Reactiver l\'annonce', 'Reactivate the ad', 1, NULL, NULL),
('Reactivation_annoce_page', 'text_btn_connecter', 'Me connecter', 'Log in', '/reactiver-annonce/{id}.{email}', 1, 'Me connecter', 'Log in', 1, NULL, NULL),
('Reactivation_annoce_page', 'message_success_reactivation', 'Annonce mise à jour avec succès', 'Successfully Updated Ad', '/reactiver-annonce/{id}.{email}', 1, 'Annonce mise à jour avec succès', 'Successfully Updated Ad', 1, NULL, NULL),
('Reactivation_annoce_page', 'message_error_reactivation', 'Annonce mise à jour avec erreur', 'Ad updated with error', '/reactiver-annonce/{id}.{email}', 1, 'Annonce mise à jour avec erreur', 'Ad updated with error', 1, NULL, NULL);


INSERT INTO `page_text` ( `page`, `index`, `text_fr`, `text_en`, `url`, `ordre`, `text_fr_proposition`, `text_en_proposition`, `valide`, `commentaire`, `id_traducteur`) VALUES
('reinitialisation-mot-de-passe', 'cependant_click', 'Afin de valider votre adresse mail et que vos annonces soient visibles cliquez sur le lien ci-dessous : Update', 'In order to validate your email address and that your ads are visible click on the link below :', '/reinitialisation-mot-de-passe', 1, 'Afin de valider votre adresse mail et que vos annonces soient visibles cliquez sur le lien ci-dessous : Update', 'In order to validate your email address and that your ads are visible click on the link below :', 1, NULL, NULL),
( 'reinitialisation-mot-de-passe', 'account_created', 'Félicitation et bienvenu votre compte a été crée .Il vous reste qu\'une dernière étape.', 'Congratulations and welcome, your account has been created. You just have one last step.', '/reinitialisation-mot-de-passe', 1, 'Félicitation et bienvenu votre compte a été crée .Il vous reste qu\'une dernière étape.', 'Congratulations and welcome, your account has been created. You just have one last step.', 1, NULL, NULL),
('reinitialisation-mot-de-passe', 'txt_click', 'Cliquez ici', 'click here', '/reinitialisation-mot-de-passe', 1, 'Cliquez ici', 'click here', 1, NULL, NULL),
('reinitialisation-mot-de-passe', 'span_click', 'pour renvoyer un mail de confirmation de compte', 'to resend an account confirmation email', '/reinitialisation-mot-de-passe', 1, 'pour renvoyer un mail de confirmation de compte', 'to resend an account confirmation email', 1, NULL, NULL);